# Generated by Django 2.1.15 on 2020-03-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cur_poll',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='displayPref',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailDelete',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailInvite',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailStart',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailStop',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='exp_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mturk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numq',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='showHint',
        ),
    ]
