# Generated by Django 2.2 on 2020-04-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programgroup',
            name='the_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.Application'),
        ),
    ]
