# Generated by Django 2.2 on 2020-04-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_programgroup_the_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programgroup',
            name='the_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.Form'),
        ),
    ]
