# Generated by Django 2.2 on 2020-04-06 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_field_is_feature'),
        ('applications', '0003_auto_20200406_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.Field')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Program')),
            ],
        ),
    ]
