# Generated by Django 2.2 on 2020-04-06 00:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='size',
            field=models.IntegerField(default=10, help_text='How many people expected in this program', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='programgroup',
            name='the_form',
            field=models.OneToOneField(help_text='The form that is used to help matching', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.Form'),
        ),
    ]
