# Generated by Django 2.2 on 2020-04-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200406_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='group',
            field=models.ForeignKey(help_text='The group which this program belong', on_delete=django.db.models.deletion.CASCADE, to='applications.ProgramGroup'),
        ),
    ]
