# Generated by Django 2.2 on 2020-04-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'Single line text'), (2, 'Text Area'), (3, 'Email'), (12, 'Integer'), (13, 'Float'), (14, 'URL'), (4, 'Check box'), (5, 'Check boxes'), (6, 'Drop down'), (7, 'Multi select'), (8, 'Radio buttons'), (9, 'File upload'), (10, 'Date'), (11, 'Date/time'), (15, 'Date of birth'), (100, 'My cool checkbox')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='form',
            name='button_text',
            field=models.CharField(default='Submit', help_text='This is the submit button which will be displayed', max_length=50, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='form',
            name='intro',
            field=models.TextField(blank=True, help_text='Form Introduction', verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='form',
            name='response',
            field=models.TextField(blank=True, default='Form submission success!', help_text='This is the response after the form has been submitted', verbose_name='Response'),
        ),
    ]
