# Generated by Django 2.2 on 2020-04-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_field_is_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Choices'),
        ),
    ]
